export * from './banner-router/banner-router.component'
export * from './footer/footer.component'
export * from './home/home.component'
export * from './navbar/navbar.component'
export * from './sobre-curso/sobre-curso.component'
